"""add bundle_category_limits

Revision ID: 12159d93d383
Revises: 5ebda9373b28
Create Date: 2026-08-05 22:57:34.609214

"""
import uuid

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '12159d93d383'
down_revision = '5ebda9373b28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bundle_category_limits', postgresql.JSONB(astext_type=sa.Text()), nullable=True))

    # ### end Alembic commands ###

    # Quinta categoría principal (ver mensaje de requerimientos actualizado).
    categories = sa.table(
        "categories",
        sa.column("id", postgresql.UUID(as_uuid=True)),
        sa.column("name", sa.String),
        sa.column("slug", sa.String),
    )
    op.execute(categories.insert().values(id=uuid.uuid4(), name="Monederos", slug="monederos"))


def downgrade():
    op.execute("DELETE FROM categories WHERE slug = 'monederos'")

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('bundle_category_limits')

    # ### end Alembic commands ###
