"""Category restructure

Revision ID: 14684c79eea9
Revises: f2a7c9e4b1d6
Create Date: 2026-09-10 14:03:30.244279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14684c79eea9'
down_revision = 'f2a7c9e4b1d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('print_type', sa.String(length=50), nullable=True))
        batch_op.alter_column('subcategory',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('ck_products_subcategory'), type_='check')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_check_constraint(batch_op.f('ck_products_subcategory'), "subcategory::text = ANY (ARRAY['Estampado animado'::character varying, 'Estampado animado 3D'::character varying, 'Estampado en yute'::character varying, 'Tricombo'::character varying, 'Mixto'::character varying]::text[])")
        batch_op.alter_column('subcategory',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.drop_column('print_type')

    # ### end Alembic commands ###
