"""add bundle_mandatory_models

Revision ID: 64dce27e8746
Revises: 14684c79eea9
Create Date: 2026-09-10 15:34:50.510127

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '64dce27e8746'
down_revision = '14684c79eea9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bundle_mandatory_models', postgresql.JSONB(astext_type=sa.Text()), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('bundle_mandatory_models')

    # ### end Alembic commands ###
