"""add material, medidas, caracteristicas

Revision ID: a3631cd7df6a
Revises: 64dce27e8746
Create Date: 2026-09-12 04:12:14.798924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3631cd7df6a'
down_revision = '64dce27e8746'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('material', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('medidas', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('caracteristicas', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('caracteristicas')
        batch_op.drop_column('medidas')
        batch_op.drop_column('material')

    # ### end Alembic commands ###
